<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Generalized linear models | Statistical analysis of designed experiments: yesterday, today, and tomorrow</title>
  <meta name="description" content="An online text in statistical analysis using the linear model" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Generalized linear models | Statistical analysis of designed experiments: yesterday, today, and tomorrow" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online text in statistical analysis using the linear model" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Generalized linear models | Statistical analysis of designed experiments: yesterday, today, and tomorrow" />
  
  <meta name="twitter:description" content="An online text in statistical analysis using the linear model" />
  

<meta name="author" content="Kevin Gross" />


<meta name="date" content="2026-10-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="non-linear-regression.html"/>
<link rel="next" href="smoothing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#philosophy"><i class="fa fa-check"></i>Philosophy</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#scope-and-coverage"><i class="fa fa-check"></i>Scope and coverage</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#mathematical-level"><i class="fa fa-check"></i>Mathematical level</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computing"><i class="fa fa-check"></i>Computing</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#llms-in-statistical-analysis"><i class="fa fa-check"></i>LLMs in statistical analysis</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#format-of-the-notes"><i class="fa fa-check"></i>Format of the notes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#a-word-on-the-title"><i class="fa fa-check"></i>A word on the title</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments-and-license"><i class="fa fa-check"></i>Acknowledgments and license</a></li>
</ul></li>
<li class="part"><span><b>Part I: Regression modeling</b></span></li>
<li class="chapter" data-level="1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>1</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#the-basics-of-slr"><i class="fa fa-check"></i><b>1.1</b> The basics of SLR</a></li>
<li class="chapter" data-level="1.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#least-squares-estimation"><i class="fa fa-check"></i><b>1.2</b> Least-squares estimation</a></li>
<li class="chapter" data-level="1.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#inference-for-the-slope"><i class="fa fa-check"></i><b>1.3</b> Inference for the slope</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#standard-errors"><i class="fa fa-check"></i><b>1.3.1</b> Standard errors</a></li>
<li class="chapter" data-level="1.3.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals"><i class="fa fa-check"></i><b>1.3.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="1.3.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#statistical-hypothesis-tests"><i class="fa fa-check"></i><b>1.3.3</b> Statistical hypothesis tests</a></li>
<li class="chapter" data-level="1.3.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#inference-for-the-intercept"><i class="fa fa-check"></i><b>1.3.4</b> Inference for the intercept</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#sums-of-squares-decomposition-and-r2"><i class="fa fa-check"></i><b>1.4</b> Sums of squares decomposition and <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="1.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#diagnostic-plots"><i class="fa fa-check"></i><b>1.5</b> Diagnostic plots</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#residuals-vs.-fitted-values"><i class="fa fa-check"></i><b>1.5.1</b> Residuals vs. fitted values</a></li>
<li class="chapter" data-level="1.5.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#residuals-vs.-predictors"><i class="fa fa-check"></i><b>1.5.2</b> Residuals vs. predictor(s)</a></li>
<li class="chapter" data-level="1.5.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#residuals-vs.-other-variables"><i class="fa fa-check"></i><b>1.5.3</b> Residuals vs. other variables</a></li>
<li class="chapter" data-level="1.5.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#normal-probability-plot"><i class="fa fa-check"></i><b>1.5.4</b> Normal probability plot</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#consequences-of-violating-model-assumptions-and-possible-fixes"><i class="fa fa-check"></i><b>1.6</b> Consequences of violating model assumptions, and possible fixes</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#linearity"><i class="fa fa-check"></i><b>1.6.1</b> Linearity</a></li>
<li class="chapter" data-level="1.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#independence"><i class="fa fa-check"></i><b>1.6.2</b> Independence</a></li>
<li class="chapter" data-level="1.6.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#constant-variance"><i class="fa fa-check"></i><b>1.6.3</b> Constant variance</a></li>
<li class="chapter" data-level="1.6.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#normality"><i class="fa fa-check"></i><b>1.6.4</b> Normality</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#prediction-with-regression-models"><i class="fa fa-check"></i><b>1.7</b> Prediction with regression models</a></li>
<li class="chapter" data-level="1.8" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#regression-design"><i class="fa fa-check"></i><b>1.8</b> Regression design</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#choice-of-predictor-values"><i class="fa fa-check"></i><b>1.8.1</b> Choice of predictor values</a></li>
<li class="chapter" data-level="1.8.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#powerSLR"><i class="fa fa-check"></i><b>1.8.2</b> Power</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#centering-the-predictor"><i class="fa fa-check"></i><b>1.9</b> <span class="math inline">\(^\star\)</span>Centering the predictor</a></li>
<li class="chapter" data-level="" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#appendix-a-fitting-the-slr-model-in-r"><i class="fa fa-check"></i>Appendix A: Fitting the SLR model in R</a></li>
<li class="chapter" data-level="" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#appendix-b-regression-models-in-sas-proc-reg"><i class="fa fa-check"></i>Appendix B: Regression models in SAS PROC REG</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>2</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple-regression.html"><a href="multiple-regression.html#multiple-regression-basics"><i class="fa fa-check"></i><b>2.1</b> Multiple regression basics</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="multiple-regression.html"><a href="multiple-regression.html#ideas-that-carry-over-from-slr-to-multiple-regression"><i class="fa fa-check"></i><b>2.1.1</b> Ideas that carry over from SLR to multiple regression</a></li>
<li class="chapter" data-level="2.1.2" data-path="multiple-regression.html"><a href="multiple-regression.html#interpreting-partial-regression-coefficients."><i class="fa fa-check"></i><b>2.1.2</b> Interpreting partial regression coefficients.</a></li>
<li class="chapter" data-level="2.1.3" data-path="multiple-regression.html"><a href="multiple-regression.html#visualizing-a-multiple-regression-model"><i class="fa fa-check"></i><b>2.1.3</b> Visualizing a multiple regression model</a></li>
<li class="chapter" data-level="2.1.4" data-path="multiple-regression.html"><a href="multiple-regression.html#statistical-inference-for-partial-regression-coefficients"><i class="fa fa-check"></i><b>2.1.4</b> Statistical inference for partial regression coefficients</a></li>
<li class="chapter" data-level="2.1.5" data-path="multiple-regression.html"><a href="multiple-regression.html#prediction"><i class="fa fa-check"></i><b>2.1.5</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="multiple-regression.html"><a href="multiple-regression.html#F-test"><i class="fa fa-check"></i><b>2.2</b> <span class="math inline">\(F\)</span>-tests for several regression coefficients</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple-regression.html"><a href="multiple-regression.html#basic-machinery"><i class="fa fa-check"></i><b>2.2.1</b> Basic machinery</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple-regression.html"><a href="multiple-regression.html#model-utility-test"><i class="fa fa-check"></i><b>2.2.2</b> Model utility test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple-regression.html"><a href="multiple-regression.html#categorical-predictors"><i class="fa fa-check"></i><b>2.3</b> Categorical predictors</a></li>
<li class="chapter" data-level="2.4" data-path="multiple-regression.html"><a href="multiple-regression.html#regression-interactions"><i class="fa fa-check"></i><b>2.4</b> Interactions between predictors</a></li>
<li class="chapter" data-level="2.5" data-path="multiple-regression.html"><a href="multiple-regression.html#collinearity"><i class="fa fa-check"></i><b>2.5</b> (Multi-)Collinearity</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="multiple-regression.html"><a href="multiple-regression.html#what-is-collinearity"><i class="fa fa-check"></i><b>2.5.1</b> What is collinearity?</a></li>
<li class="chapter" data-level="2.5.2" data-path="multiple-regression.html"><a href="multiple-regression.html#variance-inflation-factors-vifs"><i class="fa fa-check"></i><b>2.5.2</b> Variance inflation factors (VIFs)</a></li>
<li class="chapter" data-level="2.5.3" data-path="multiple-regression.html"><a href="multiple-regression.html#coping-with-collinearity"><i class="fa fa-check"></i><b>2.5.3</b> Coping with collinearity</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="multiple-regression.html"><a href="multiple-regression.html#variable-selection-choosing-the-best-model"><i class="fa fa-check"></i><b>2.6</b> Variable selection: Choosing the best model</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="multiple-regression.html"><a href="multiple-regression.html#model-selection-and-inference"><i class="fa fa-check"></i><b>2.6.1</b> Model selection and inference</a></li>
<li class="chapter" data-level="2.6.2" data-path="multiple-regression.html"><a href="multiple-regression.html#ranking-methods"><i class="fa fa-check"></i><b>2.6.2</b> Ranking methods</a></li>
<li class="chapter" data-level="2.6.3" data-path="multiple-regression.html"><a href="multiple-regression.html#sequential-methods"><i class="fa fa-check"></i><b>2.6.3</b> Sequential methods</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="multiple-regression.html"><a href="multiple-regression.html#leverage-influential-points-and-standardized-residuals"><i class="fa fa-check"></i><b>2.7</b> Leverage, influential points, and standardized residuals</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="multiple-regression.html"><a href="multiple-regression.html#leverage"><i class="fa fa-check"></i><b>2.7.1</b> Leverage</a></li>
<li class="chapter" data-level="2.7.2" data-path="multiple-regression.html"><a href="multiple-regression.html#standardized-residuals"><i class="fa fa-check"></i><b>2.7.2</b> Standardized residuals</a></li>
<li class="chapter" data-level="2.7.3" data-path="multiple-regression.html"><a href="multiple-regression.html#cooks-distance"><i class="fa fa-check"></i><b>2.7.3</b> Cook’s distance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#appendix-regression-as-a-linear-algebra-problem"><i class="fa fa-check"></i>Appendix: Regression as a linear algebra problem</a>
<ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#singular-or-pathological-design-matrices"><i class="fa fa-check"></i>Singular, or pathological, design matrices</a></li>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#additional-results"><i class="fa fa-check"></i>Additional results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="non-linear-regression.html"><a href="non-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Non-linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="non-linear-regression.html"><a href="non-linear-regression.html#polynomial-regression"><i class="fa fa-check"></i><b>3.1</b> Polynomial regression</a></li>
<li class="chapter" data-level="3.2" data-path="non-linear-regression.html"><a href="non-linear-regression.html#nls"><i class="fa fa-check"></i><b>3.2</b> Non-linear least squares</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>4</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>4.1</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#individual-binary-responses-donner-party-data"><i class="fa fa-check"></i><b>4.1.1</b> Individual binary responses: Donner party data</a></li>
<li class="chapter" data-level="4.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#individual-binary-responses-tb-in-boar"><i class="fa fa-check"></i><b>4.1.2</b> Individual binary responses: TB in boar</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>4.2</b> Poisson regression</a></li>
</ul></li>
<li class="part"><span><b>Part II: Statistical learning</b></span></li>
<li class="chapter" data-level="5" data-path="smoothing.html"><a href="smoothing.html"><i class="fa fa-check"></i><b>5</b> Smoothing</a>
<ul>
<li class="chapter" data-level="5.1" data-path="smoothing.html"><a href="smoothing.html#nearest-neighbor-methods"><i class="fa fa-check"></i><b>5.1</b> Nearest-neighbor methods</a></li>
<li class="chapter" data-level="5.2" data-path="smoothing.html"><a href="smoothing.html#loess-smoothers"><i class="fa fa-check"></i><b>5.2</b> Loess smoothers</a></li>
<li class="chapter" data-level="5.3" data-path="smoothing.html"><a href="smoothing.html#splines"><i class="fa fa-check"></i><b>5.3</b> Splines</a></li>
<li class="chapter" data-level="5.4" data-path="smoothing.html"><a href="smoothing.html#generalized-additive-models-gams"><i class="fa fa-check"></i><b>5.4</b> Generalized additive models (GAMs)</a></li>
</ul></li>
<li class="part"><span><b>Part III: Designed experiments</b></span></li>
<li class="chapter" data-level="6" data-path="one-way.html"><a href="one-way.html"><i class="fa fa-check"></i><b>6</b> One-factor layout</a>
<ul>
<li class="chapter" data-level="6.1" data-path="one-way.html"><a href="one-way.html#grouped-data-and-the-design-of-experiments-doe-an-overview"><i class="fa fa-check"></i><b>6.1</b> Grouped data and the design of experiments (DoE): an overview</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="one-way.html"><a href="one-way.html#a-vocabulary-for-describing-designed-experiments"><i class="fa fa-check"></i><b>6.1.1</b> A vocabulary for describing designed experiments</a></li>
<li class="chapter" data-level="6.1.2" data-path="one-way.html"><a href="one-way.html#roadmap"><i class="fa fa-check"></i><b>6.1.2</b> Roadmap</a></li>
<li class="chapter" data-level="6.1.3" data-path="one-way.html"><a href="one-way.html#the-simplest-experiment"><i class="fa fa-check"></i><b>6.1.3</b> The simplest experiment</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="one-way.html"><a href="one-way.html#one-factor-anova"><i class="fa fa-check"></i><b>6.2</b> One-factor ANOVA</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="one-way.html"><a href="one-way.html#f-test-to-compare-means"><i class="fa fa-check"></i><b>6.2.1</b> <span class="math inline">\(F\)</span>-test to compare means</a></li>
<li class="chapter" data-level="6.2.2" data-path="one-way.html"><a href="one-way.html#connections-between-one-factor-anova-and-other-statistical-procedures"><i class="fa fa-check"></i><b>6.2.2</b> Connections between one-factor ANOVA and other statistical procedures</a></li>
<li class="chapter" data-level="6.2.3" data-path="one-way.html"><a href="one-way.html#assumptions-in-anova"><i class="fa fa-check"></i><b>6.2.3</b> Assumptions in ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="one-way.html"><a href="one-way.html#contrasts"><i class="fa fa-check"></i><b>6.3</b> Contrasts of group means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="one-way.html"><a href="one-way.html#simple-contrasts"><i class="fa fa-check"></i><b>6.3.1</b> Simple contrasts</a></li>
<li class="chapter" data-level="6.3.2" data-path="one-way.html"><a href="one-way.html#complex-contrasts"><i class="fa fa-check"></i><b>6.3.2</b> Complex contrasts</a></li>
<li class="chapter" data-level="6.3.3" data-path="one-way.html"><a href="one-way.html#orthogonal-contrasts"><i class="fa fa-check"></i><b>6.3.3</b> Orthogonal contrasts</a></li>
<li class="chapter" data-level="6.3.4" data-path="one-way.html"><a href="one-way.html#polynomial-contrasts"><i class="fa fa-check"></i><b>6.3.4</b> Polynomial contrasts</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="one-way.html"><a href="one-way.html#multiple-testing"><i class="fa fa-check"></i><b>6.4</b> Multiple comparisons</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="one-way.html"><a href="one-way.html#multiple-testing-in-general"><i class="fa fa-check"></i><b>6.4.1</b> Multiple testing in general</a></li>
<li class="chapter" data-level="6.4.2" data-path="one-way.html"><a href="one-way.html#bonferroni-and-bonferroni-like-procedures"><i class="fa fa-check"></i><b>6.4.2</b> Bonferroni and Bonferroni-like procedures</a></li>
<li class="chapter" data-level="6.4.3" data-path="one-way.html"><a href="one-way.html#multiple-comparisons-in-anova"><i class="fa fa-check"></i><b>6.4.3</b> Multiple comparisons in ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="one-way.html"><a href="one-way.html#starpower-and-sample-size-determination-in-anova"><i class="fa fa-check"></i><b>6.5</b> <span class="math inline">\(^\star\)</span>Power and sample-size determination in ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="one-way.html"><a href="one-way.html#sas-contrasts"><i class="fa fa-check"></i><b>6.6</b> Using SAS: The effects parameterization of the one-factor ANOVA</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="one-way.html"><a href="one-way.html#one-factor-effects-model"><i class="fa fa-check"></i><b>6.6.1</b> Effects-model parameterization of the one-factor ANOVA model</a></li>
<li class="chapter" data-level="6.6.2" data-path="one-way.html"><a href="one-way.html#coding-contrasts-in-proc-glm"><i class="fa fa-check"></i><b>6.6.2</b> Coding contrasts in PROC GLM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-experiments.html"><a href="factorial-experiments.html"><i class="fa fa-check"></i><b>7</b> Factorial experiments</a>
<ul>
<li class="chapter" data-level="7.1" data-path="factorial-experiments.html"><a href="factorial-experiments.html#combining-factors-crossed-vs.-nested-designs"><i class="fa fa-check"></i><b>7.1</b> Combining factors: Crossed vs. nested designs</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-experiments.html"><a href="factorial-experiments.html#two-factor-anova"><i class="fa fa-check"></i><b>7.2</b> Two-factor ANOVA</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-experiments.html"><a href="factorial-experiments.html#interaction-plots"><i class="fa fa-check"></i><b>7.2.1</b> Interaction plots</a></li>
<li class="chapter" data-level="7.2.2" data-path="factorial-experiments.html"><a href="factorial-experiments.html#getting-organized-notation-and-bookkeeping"><i class="fa fa-check"></i><b>7.2.2</b> Getting organized: Notation and bookkeeping</a></li>
<li class="chapter" data-level="7.2.3" data-path="factorial-experiments.html"><a href="factorial-experiments.html#anova-f-tests"><i class="fa fa-check"></i><b>7.2.3</b> ANOVA <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="7.2.4" data-path="factorial-experiments.html"><a href="factorial-experiments.html#an-example-with-a-significant-interaction"><i class="fa fa-check"></i><b>7.2.4</b> An example with a significant interaction</a></li>
<li class="chapter" data-level="7.2.5" data-path="factorial-experiments.html"><a href="factorial-experiments.html#two-factor-effects-model"><i class="fa fa-check"></i><b>7.2.5</b> The effects model for a two-factor ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-experiments.html"><a href="factorial-experiments.html#unreplicated-designs"><i class="fa fa-check"></i><b>7.3</b> Unreplicated factorial designs</a></li>
<li class="chapter" data-level="7.4" data-path="factorial-experiments.html"><a href="factorial-experiments.html#more-than-two-factors"><i class="fa fa-check"></i><b>7.4</b> More than two factors</a></li>
<li class="chapter" data-level="7.5" data-path="factorial-experiments.html"><a href="factorial-experiments.html#analysis-using-proc-glm-in-sas"><i class="fa fa-check"></i><b>7.5</b> Analysis using PROC GLM in SAS</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8</b> ANCOVA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ancova.html"><a href="ancova.html#common-slopes-model"><i class="fa fa-check"></i><b>8.1</b> Common-slopes model</a></li>
<li class="chapter" data-level="8.2" data-path="ancova.html"><a href="ancova.html#separate-slopes-model"><i class="fa fa-check"></i><b>8.2</b> Separate-slopes model</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html#further-reading"><i class="fa fa-check"></i><b>8.3</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="random-effects.html"><a href="random-effects.html"><i class="fa fa-check"></i><b>9</b> Random effects</a>
<ul>
<li class="chapter" data-level="9.1" data-path="random-effects.html"><a href="random-effects.html#fixed-vs.-random-effects-the-big-picture"><i class="fa fa-check"></i><b>9.1</b> Fixed vs. random effects: the big picture</a></li>
<li class="chapter" data-level="9.2" data-path="random-effects.html"><a href="random-effects.html#random-effects-models"><i class="fa fa-check"></i><b>9.2</b> Random-effects models</a></li>
<li class="chapter" data-level="9.3" data-path="random-effects.html"><a href="random-effects.html#subsampling"><i class="fa fa-check"></i><b>9.3</b> Subsampling</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="random-effects.html"><a href="random-effects.html#equal-subsamples-per-eu"><i class="fa fa-check"></i><b>9.3.1</b> Equal subsamples per EU</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="random-effects.html"><a href="random-effects.html#starmathematical-foundations"><i class="fa fa-check"></i><b>9.4</b> <span class="math inline">\(^\star\)</span>Mathematical foundations</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="random-effects.html"><a href="random-effects.html#probability-refresher"><i class="fa fa-check"></i><b>9.4.1</b> Probability refresher</a></li>
<li class="chapter" data-level="9.4.2" data-path="random-effects.html"><a href="random-effects.html#application-to-models-with-random-effects"><i class="fa fa-check"></i><b>9.4.2</b> Application to models with random effects</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="blocked-designs.html"><a href="blocked-designs.html"><i class="fa fa-check"></i><b>10</b> Blocked designs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="blocked-designs.html"><a href="blocked-designs.html#randomized-complete-block-designs"><i class="fa fa-check"></i><b>10.1</b> Randomized complete block designs</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="blocked-designs.html"><a href="blocked-designs.html#should-a-blocking-factor-be-a-fixed-or-random-effect"><i class="fa fa-check"></i><b>10.1.1</b> *Should a blocking factor be a fixed or random effect?</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="blocked-designs.html"><a href="blocked-designs.html#latin-squares-designs"><i class="fa fa-check"></i><b>10.2</b> Latin-squares designs</a></li>
<li class="chapter" data-level="10.3" data-path="blocked-designs.html"><a href="blocked-designs.html#split-plot-designs"><i class="fa fa-check"></i><b>10.3</b> Split-plot designs</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="blocked-designs.html"><a href="blocked-designs.html#denominator-degrees-of-freedom-in-split-plot-designs-and-the-satterthwaite-approximation"><i class="fa fa-check"></i><b>10.3.1</b> Denominator degrees of freedom in split-plot designs and the Satterthwaite approximation</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="blocked-designs.html"><a href="blocked-designs.html#repeated-measures"><i class="fa fa-check"></i><b>10.4</b> Repeated measures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical analysis of designed experiments: yesterday, today, and tomorrow</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Generalized linear models<a href="generalized-linear-models.html#generalized-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Generalized linear modes extend the machinery of the “general linear model” (regression and ANOVA) to data sets in which the response variable may have a non-Gaussian distribution. Generalized linear models do not encompass all possible distributions for the response variable. Instead, the distribution of the response variable must belong to a group of distributions known as the “exponential family”. (Confusingly, there is also such a thing as an exponential distribution. The exponential distribution is a member of the exponential family, but it is not the only one.) The exponential family of distributions includes many of the distributions that we encounter in practical data analysis, including Poisson, negative binomial, binomial, gamma, and beta distributions. The Gaussian distribution is included in the exponential family as well. One notable distribution that is not part of the exponential family is the <span class="math inline">\(t\)</span>-distribution. Distributions in the exponential family all have a common mathematical structure, and thus can be handled with a unified fitting scheme.</p>
<p>In practice, logistic regression (with binomial responses) and Poisson regression are far and away the two most common forms of generalized linear models that one encounters. You can go far with only knowing these two examples of generalized linear models.</p>
<div id="logistic-regression" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Logistic regression<a href="generalized-linear-models.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We generally distinguish between two types of data with binary responses: Data in which each individual record is a separate a binary response, and data in which each record consists of a group of binary observations. The same methods can be used for either type of data. We will begin by studying two data sets with individual binary responses</p>
<div id="individual-binary-responses-donner-party-data" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Individual binary responses: Donner party data<a href="generalized-linear-models.html#individual-binary-responses-donner-party-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Donner party was a well-known group of settlers who got stuck in the Sierra Nevada snows in the winter of 1846-47. The Donner party included 45 adults (defined here as individuals at least 15 years of age), of whom only 20 survived the famous winter <span class="citation">Grayson (<a href="#ref-grayson1993differential">1993</a>)</span>. We have a data set that includes age, gender, and fate for all 45 members of the party. Here’s a look at the data set:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="generalized-linear-models.html#cb134-1" tabindex="-1"></a>donner <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/donner.txt&quot;</span>, <span class="at">head =</span> T, <span class="at">stringsAsFactors =</span> T)</span>
<span id="cb134-2"><a href="generalized-linear-models.html#cb134-2" tabindex="-1"></a><span class="fu">summary</span>(donner)</span></code></pre></div>
<pre><code>##       age           sex           fate   
##  Min.   :15.0   female:15   died    :25  
##  1st Qu.:24.0   male  :30   survived:20  
##  Median :28.0                            
##  Mean   :31.8                            
##  3rd Qu.:40.0                            
##  Max.   :65.0</code></pre>
<p>Suppose we want to model the relationship between age, gender, and fate, where age and gender are predictors, and fate is the response. Fate is a binary response because it has only two possible values.</p>
<p>Our goal is to relate the predictors to the probability of one outcome or the other. The challenge in doing so is that probabilities are constrained to take values between 0 and 1, and are thus awkward to work with mathematically. Instead, we model the log odds of oue outcome for the other. To explain log odds, we first need to explain odds.</p>
<p>Suppose that the probability of an event occurring is <span class="math inline">\(p\)</span>. The odds of that event occurring are
<span class="math display">\[
\mathrm{odds} = \dfrac{p}{1-p}
\]</span>
The logit, or log odds are simply the natural log of the odds, or
<span class="math display">\[
\mathrm{logit} = \ln \mathrm{odds} = \ln(\dfrac{p}{1-p}).
\]</span></p>
<p>We can work backwards from log odds or odds to probabilities by inverting the formulas above. Going from log odds to odds is easy:
<span class="math display">\[
\mathrm{odds} = e^{\mathrm{logit}}.
\]</span>
Going from odds to probabilities is also easy:
<span class="math display">\[
p = \dfrac{\mathrm{odds}}{1 + \mathrm{odds}}
\]</span></p>
<p>Now, we can use
<span class="math display">\[
\mathrm{logit}(p) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \ldots,
\]</span>
which will work just fine.</p>
<p>In R, we can fit this model using the <code>glm</code> command. The <code>glm</code> program fits [g]eneralized [l]inear [m]odels. The <code>glm</code> command includes an additional <code>family</code> argument, which is where we specify the distribution of the response. With binary responses, the distribution is the <code>binomial</code> family.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="generalized-linear-models.html#cb136-1" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(fate <span class="sc">~</span> age <span class="sc">+</span> sex, <span class="at">family =</span> binomial, <span class="at">data =</span> donner)</span>
<span id="cb136-2"><a href="generalized-linear-models.html#cb136-2" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = fate ~ age + sex, family = binomial, data = donner)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  3.23041    1.38686   2.329   0.0198 *
## age         -0.07820    0.03728  -2.097   0.0359 *
## sexmale     -1.59729    0.75547  -2.114   0.0345 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 61.827  on 44  degrees of freedom
## Residual deviance: 51.256  on 42  degrees of freedom
## AIC: 57.256
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>To interpret the output correctly, it is critical to know whether the software is modeling the probability of an individual dying or of an individual surviving. As far as I can tell, there’s no great way to figure this out. Some online documentation suggests that <code>glm</code> will model the probability of the outcome listed second following a call to the <code>levels</code> command. Let’s try it.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="generalized-linear-models.html#cb138-1" tabindex="-1"></a><span class="fu">levels</span>(donner<span class="sc">$</span>fate)</span></code></pre></div>
<pre><code>## [1] &quot;died&quot;     &quot;survived&quot;</code></pre>
<p>So, the model above is modeling the log odds of surviving. That seems less morbid than modeling the log odds of dying, so we’ll stick with it. (It turns out that a model for the log odds of dying would generate the same parameter estimates, albeit with all the signs reversed.)</p>
<p>We can interpret the model parameters in the same way that we interpret parameters from a multiple regression model, just remembering that we’re thinking about the log odds of surviving as the response. For example, the parameter associated with <code>age</code> tells us that when we compare two people of different ages but of the same sex, the older individual’s log odds of surviving will be 0.078 less for every additional year of age. (So 0.078 less if the older individual is one year older, <span class="math inline">\(2 \times 0.078 = 0.156\)</span> less if the individual is two years older, and so on.)</p>
<p>While it’s quite hard to think on a log odds scale, note that log odds and probabilities move in the same direction. So, if older folks have a lower log odds of surviving, then they also have a lower probability of surviving.</p>
<p>It’s good practice to work out the probabilities of surviving for a few test cases. For example, here’s how we’d compute the predicted survival probability for a 30-year old man.
<span class="math display">\[
\begin{align}
\mathrm{logit} &amp; = \hat{\beta}_0 + \hat{\beta}_1 \times 30 + \hat{\beta}_2 \times 1 = -0.713 \\
\mathrm{odds} &amp; =e^{-0.713} = 0.49\\
\mathrm{probability} &amp; = 0.49/1.49 = 0.33.
\end{align}
\]</span></p>
<p>Sometimes we interpret the logistic regression parameters in terms of the odds ratio. In the logistic regression model, if we hold all other predictors constant and increase the predictor <span class="math inline">\(x_i\)</span> by 1, then the predicted odds of success are multiplied by the factor <span class="math inline">\(e^{\beta_i}\)</span>. This is called the odds ratio for predictor <span class="math inline">\(i\)</span>. For the Donner party data, the odds ratio associated with age is <span class="math inline">\(e^{-0.078} = 0.925\)</span>, so that each additional year of age (when comparing two people of the same sex) decreases the odds by a multiplicative factor of 0.925. Or, if you prefer, the odds decrease by 7.5% for every additional year of age.</p>
<p>For generalized linear models, there are several different tests that we can use for statistical significance. The <code>glm</code> output reports a <span class="math inline">\(z\)</span>-test, for which the test statistic is simply the estimate divided by the standard error, and the <span class="math inline">\(p\)</span>-value is found by comparison to a standard normal distribution. (Remember that by “standard” normal distribution, we mean a normal distribution with a mean of 0 and a variance of 1. Remember also that statisticians usually reserve the notation <span class="math inline">\(z\)</span> for the standard normal distribution.)</p>
<hr />
<p><span style="color: gray;"> In generalized linear models, parameter estimates are found by a scheme called maximum likelihood estimation. In maximum likelihood estimation, the model is used to construct an objective function called the likelihood, in which large values of the likelihood indicate a better fit. Some call the likelihood a “goodness-of-fit” metric. The maximum likelihood estimates, or MLEs, are the values of the parameters that (you guessed it) maximize this likelihood. (Actually, its computationally easier to maximize the log-likelihood, but the values that maximize the log-likelihood will also be the values that maximize the likelihood.) The MLEs are found by an optimization algorithm, which is the mysterious “Fisher scoring” reported at the end of the <code>glm</code> summary. Standard errors of parameter estimates are found by inverting the Hessian (or matrix of second derivatves) of the log-likelihood function at the MLEs.</span></p>
<hr />
<p>The model as we have it so far is additive on the log-odds scale. Note that an additive model on the log-odds scale necessarily is non-additive on the probability scale. For example, in this case, if we compare a man to a woman of the same age, the man’s log odds of survival will always be -1.60 less. The difference between the equivalent probabilities will depend on the particular age of the two individuals being compared.</p>
<p>We can still test for an interaction between age and sex on the log odds scale. If nothing else, this model is more flexible and so it might provide a significantly better fit. Let’s see.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="generalized-linear-models.html#cb140-1" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(fate <span class="sc">~</span> age <span class="sc">*</span> sex, <span class="at">family =</span> binomial, <span class="at">data =</span> donner)</span>
<span id="cb140-2"><a href="generalized-linear-models.html#cb140-2" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = fate ~ age * sex, family = binomial, data = donner)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  7.24638    3.20517   2.261   0.0238 *
## age         -0.19407    0.08742  -2.220   0.0264 *
## sexmale     -6.92805    3.39887  -2.038   0.0415 *
## age:sexmale  0.16160    0.09426   1.714   0.0865 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 61.827  on 44  degrees of freedom
## Residual deviance: 47.346  on 41  degrees of freedom
## AIC: 55.346
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The interaction is not significant at the usual 5% threshold for significance, so we’ll revert to the additive model.</p>
</div>
<div id="individual-binary-responses-tb-in-boar" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Individual binary responses: TB in boar<a href="generalized-linear-models.html#individual-binary-responses-tb-in-boar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here’s a second example of logistic regression. Something interesting and different will happen in these data.</p>
<p>This is a data set analyzed by <span class="citation">Zuur et al. (<a href="#ref-zuur2009mixed">2009</a>)</span>. As explained there, these data describe the incidence of “tuberculosis-like lesions in wild boar <em>Sus scrofa</em>” in southern Spain, and were originally collected by <span class="citation">Vicente et al. (<a href="#ref-vicente2006wild">2006</a>)</span>. The potential explanatory variables in the data set include a measure of the animal’s size, it’s sex, and a grouping into one of four age classes.</p>
<p>Let’s load the data, do some housekeeping, and have a look at the data set:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="generalized-linear-models.html#cb142-1" tabindex="-1"></a>boar <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/boar.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb142-2"><a href="generalized-linear-models.html#cb142-2" tabindex="-1"></a></span>
<span id="cb142-3"><a href="generalized-linear-models.html#cb142-3" tabindex="-1"></a><span class="co"># remove incomplete records</span></span>
<span id="cb142-4"><a href="generalized-linear-models.html#cb142-4" tabindex="-1"></a>boar <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(boar)</span>
<span id="cb142-5"><a href="generalized-linear-models.html#cb142-5" tabindex="-1"></a></span>
<span id="cb142-6"><a href="generalized-linear-models.html#cb142-6" tabindex="-1"></a><span class="co"># convert sex to a factor</span></span>
<span id="cb142-7"><a href="generalized-linear-models.html#cb142-7" tabindex="-1"></a>boar<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(boar<span class="sc">$</span>SEX)</span>
<span id="cb142-8"><a href="generalized-linear-models.html#cb142-8" tabindex="-1"></a></span>
<span id="cb142-9"><a href="generalized-linear-models.html#cb142-9" tabindex="-1"></a><span class="fu">names</span>(boar) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tb&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;length&quot;</span>)</span>
<span id="cb142-10"><a href="generalized-linear-models.html#cb142-10" tabindex="-1"></a><span class="fu">summary</span>(boar)</span></code></pre></div>
<pre><code>##        tb         sex          age            length     
##  Min.   :0.0000   1:206   Min.   :1.000   Min.   : 46.5  
##  1st Qu.:0.0000   2:288   1st Qu.:3.000   1st Qu.:107.0  
##  Median :0.0000           Median :3.000   Median :122.0  
##  Mean   :0.4575           Mean   :3.142   Mean   :117.3  
##  3rd Qu.:1.0000           3rd Qu.:4.000   3rd Qu.:130.4  
##  Max.   :1.0000           Max.   :4.000   Max.   :165.0</code></pre>
<p>We’ll fit the usual logistic regression model first, considering only the animal’s size as a predictor. Size in this case is a measure of the length of the animal, in cm. (Check it out, these are some big pigs.)</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="generalized-linear-models.html#cb144-1" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length, <span class="at">family =</span> binomial, <span class="at">data =</span> boar)</span>
<span id="cb144-2"><a href="generalized-linear-models.html#cb144-2" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length, family = binomial, data = boar)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.137107   0.695381  -5.949 2.69e-09 ***
## length       0.033531   0.005767   5.814 6.09e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 641.23  on 492  degrees of freedom
## AIC: 645.23
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>For these data, the response (<code>tb</code>) is coded as zeros and ones. When <code>glm</code> is given a response coded thusly, it always models the probability of the outcome labeled with a one. In this case, zeros code for uninfected animals and ones code for infected animals, so we are modeling the probability of infection. Our model suggests that bigger boar are more likely to be infected, and the effect is crazy significant.</p>
<p>Here’s some R code to plot the model’s fit on a probability scale. It takes a bit of work, but probabilities are so much easier to understand than log odds. If these were your data, it’d be worth the extra effort.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="generalized-linear-models.html#cb146-1" tabindex="-1"></a><span class="fu">with</span>(boar, <span class="fu">plot</span>(tb <span class="sc">~</span> length))</span>
<span id="cb146-2"><a href="generalized-linear-models.html#cb146-2" tabindex="-1"></a></span>
<span id="cb146-3"><a href="generalized-linear-models.html#cb146-3" tabindex="-1"></a><span class="co"># add a line for the fitted probabilities of tb</span></span>
<span id="cb146-4"><a href="generalized-linear-models.html#cb146-4" tabindex="-1"></a></span>
<span id="cb146-5"><a href="generalized-linear-models.html#cb146-5" tabindex="-1"></a>new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">length =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(boar<span class="sc">$</span>length),</span>
<span id="cb146-6"><a href="generalized-linear-models.html#cb146-6" tabindex="-1"></a>                                    <span class="at">to   =</span> <span class="fu">max</span>(boar<span class="sc">$</span>length),</span>
<span id="cb146-7"><a href="generalized-linear-models.html#cb146-7" tabindex="-1"></a>                                    <span class="at">length =</span> <span class="dv">100</span>))</span>
<span id="cb146-8"><a href="generalized-linear-models.html#cb146-8" tabindex="-1"></a></span>
<span id="cb146-9"><a href="generalized-linear-models.html#cb146-9" tabindex="-1"></a>predict.fm1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb146-10"><a href="generalized-linear-models.html#cb146-10" tabindex="-1"></a></span>
<span id="cb146-11"><a href="generalized-linear-models.html#cb146-11" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>length, <span class="at">y =</span> predict.fm1<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb146-12"><a href="generalized-linear-models.html#cb146-12" tabindex="-1"></a></span>
<span id="cb146-13"><a href="generalized-linear-models.html#cb146-13" tabindex="-1"></a><span class="co"># add lines for standard errors</span></span>
<span id="cb146-14"><a href="generalized-linear-models.html#cb146-14" tabindex="-1"></a><span class="co"># use critical value from z distribution here because</span></span>
<span id="cb146-15"><a href="generalized-linear-models.html#cb146-15" tabindex="-1"></a><span class="co"># the scale parameter is not estimated</span></span>
<span id="cb146-16"><a href="generalized-linear-models.html#cb146-16" tabindex="-1"></a></span>
<span id="cb146-17"><a href="generalized-linear-models.html#cb146-17" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>length, </span>
<span id="cb146-18"><a href="generalized-linear-models.html#cb146-18" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb146-19"><a href="generalized-linear-models.html#cb146-19" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb146-20"><a href="generalized-linear-models.html#cb146-20" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb146-21"><a href="generalized-linear-models.html#cb146-21" tabindex="-1"></a></span>
<span id="cb146-22"><a href="generalized-linear-models.html#cb146-22" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>length, </span>
<span id="cb146-23"><a href="generalized-linear-models.html#cb146-23" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb146-24"><a href="generalized-linear-models.html#cb146-24" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb146-25"><a href="generalized-linear-models.html#cb146-25" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="04-GeneralizedLinearModels_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Now let’s try adding sex and age class as predictors. Because the age class is coded with values 1–4, we want to make sure that R treats these values as levels of a categorical predictor (and not a quantitative predictor), so we enclose the <code>age</code> predictor in <code>as.factor(age)</code>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="generalized-linear-models.html#cb147-1" tabindex="-1"></a><span class="co"># fit a model with sex, age (as a categorical predictor) and their interaction</span></span>
<span id="cb147-2"><a href="generalized-linear-models.html#cb147-2" tabindex="-1"></a></span>
<span id="cb147-3"><a href="generalized-linear-models.html#cb147-3" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length <span class="sc">+</span> sex <span class="sc">*</span> <span class="fu">as.factor</span>(age),</span>
<span id="cb147-4"><a href="generalized-linear-models.html#cb147-4" tabindex="-1"></a>           <span class="at">family =</span> binomial,</span>
<span id="cb147-5"><a href="generalized-linear-models.html#cb147-5" tabindex="-1"></a>           <span class="at">data =</span> boar)</span>
<span id="cb147-6"><a href="generalized-linear-models.html#cb147-6" tabindex="-1"></a></span>
<span id="cb147-7"><a href="generalized-linear-models.html#cb147-7" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length + sex * as.factor(age), family = binomial, 
##     data = boar)
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)          -16.55356  724.50177  -0.023    0.982
## length                 0.01840    0.01253   1.469    0.142
## sex2                  14.19739  724.50190   0.020    0.984
## as.factor(age)2       13.83446  724.50169   0.019    0.985
## as.factor(age)3       14.31136  724.50191   0.020    0.984
## as.factor(age)4       14.68141  724.50219   0.020    0.984
## sex2:as.factor(age)2 -14.53254  724.50204  -0.020    0.984
## sex2:as.factor(age)3 -14.36861  724.50196  -0.020    0.984
## sex2:as.factor(age)4 -14.53354  724.50196  -0.020    0.984
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 635.43  on 485  degrees of freedom
## AIC: 653.43
## 
## Number of Fisher Scoring iterations: 14</code></pre>
<p>It’s pandemonium! Something has gone wickedly wrong here. Notice how wild the standard errors are.</p>
<p>To figure out what went wrong, we need to do a bit of detective work. Let’s back up and try to figure out how many boar were infected in each combination of sex and age class. We can compute the appropriate tallies with the <code>table</code> command; we’ll be stylish at use the <code>with</code> command to write some pretty code:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="generalized-linear-models.html#cb149-1" tabindex="-1"></a><span class="fu">with</span>(boar, <span class="fu">table</span>(tb, age, sex))</span></code></pre></div>
<pre><code>## , , sex = 1
## 
##    age
## tb   1  2  3  4
##   0  4 37 37 28
##   1  0 14 34 52
## 
## , , sex = 2
## 
##    age
## tb   1  2  3  4
##   0  7 40 62 53
##   1  2 11 48 65</code></pre>
<p>And here is our problem. Our problematic model included an interaction between the categorical predictors <code>age</code> and <code>sex</code>, and a numerical predictor for <code>length</code>. So, if we were to make a picture of the model, on a log odds scale the model has 8 parallel lines: one for each combination of <code>age</code> and <code>sex</code>. But of the 4 boar of the sex coded by a 1 (whichever sex that is), and in age class 1, none of the 4 are infected, so the empirical probability of infection is 0. Yet on a log odds scale, a probability of 0 corresponds to a log odds of <span class="math inline">\(-\infty\)</span>. The model can’t handle log odds of <span class="math inline">\(-\infty\)</span>, and so it returns nonsense.</p>
<hr />
<p><span style="color: gray;"> We can do better than just say that the model output is nonsense. In cases of complete separation, though, the likelihood function is pathological in the sense that the maximizing parameter estimates are found at either <span class="math inline">\(+\infty\)</span> or <span class="math inline">\(-\infty\)</span>. In this case, the <code>glm</code> program works for awhile, and then kicks out after it goes through a predetermined maximum number of iterations without converging on the likelihood-maximizing estimates. The estimates that we saw when we looked at the summary of <code>fm2</code> were just the parameter values at the last iteration before the program stopped. The clearest tell-tale sign that the algorithm has failed to converge is the large standard errors. Remember that the standard errors are the inverse of the Hessian, and remember that the Hessian tells you something about the curvature of the log-likelihood function. When the standard errors are very large, the curvature of the log-likelihood is very small, meaning that the log-likelihood is essentially flat.</span></p>
<hr />
<p>This is an example of “complete separation”. Complete separation happens when there are predictor values, or combinations of predictor values, that completely separate one of the two outcomes being modeled from the other. In this case, the model fitting fails because the model is trying to generate fitted log odds of <span class="math inline">\(+\infty\)</span> or <span class="math inline">\(-\infty\)</span>.</p>
<p>Complete separation happens, especially in data sets (like this one) with several categorical predictors. It must be dealt with; the model <code>fm2</code> above is nonsense. There are several possible remedies here. The first is to try to reduce the number of parameters in the model, perhaps by eliminating the interaction between sex and age class.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="generalized-linear-models.html#cb151-1" tabindex="-1"></a><span class="co"># fit a model with sex, age (as a categorical predictor) and their interaction</span></span>
<span id="cb151-2"><a href="generalized-linear-models.html#cb151-2" tabindex="-1"></a></span>
<span id="cb151-3"><a href="generalized-linear-models.html#cb151-3" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(tb <span class="sc">~</span> length <span class="sc">+</span> sex <span class="sc">+</span> <span class="fu">as.factor</span>(age),</span>
<span id="cb151-4"><a href="generalized-linear-models.html#cb151-4" tabindex="-1"></a>            <span class="at">family =</span> binomial,</span>
<span id="cb151-5"><a href="generalized-linear-models.html#cb151-5" tabindex="-1"></a>            <span class="at">data =</span> boar)</span>
<span id="cb151-6"><a href="generalized-linear-models.html#cb151-6" tabindex="-1"></a></span>
<span id="cb151-7"><a href="generalized-linear-models.html#cb151-7" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = tb ~ length + sex + as.factor(age), family = binomial, 
##     data = boar)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)     -2.67730    1.07306  -2.495   0.0126 *
## length           0.01959    0.01237   1.584   0.1133  
## sex2            -0.24297    0.19354  -1.255   0.2093  
## as.factor(age)2 -0.19847    0.92641  -0.214   0.8304  
## as.factor(age)3  0.33908    1.06938   0.317   0.7512  
## as.factor(age)4  0.59041    1.20582   0.490   0.6244  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 681.25  on 493  degrees of freedom
## Residual deviance: 637.41  on 488  degrees of freedom
## AIC: 649.41
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>For these data, this works. In other cases, a second option is to use so-called “exact” methods for inference. There doesn’t appear to be a good package available for implementing these methods in R. Other software packages might be necessary.</p>
<!-- ### Grouped binary data: Industrial melanism -->
<!-- We'll start with the standard logistic regression model for the industrial melanism data.  We are primarily interested in determining if the effect of color morph on removal rate changes with distance from Liverpool.  For grouped binary data, we need to specify both the number of "successes" and number of "failures" as the response variable in the model.  Here, we use `cbind` to create a two-column matrix with the number of "successes" (moths removed) in the first column, and the number of "failures" (moths not removed) in the second column.  See the help documentation for `glm` for more details. -->
<!-- ```{r} -->
<!-- moth <- read.table("data/moth.txt", head = TRUE, stringsAsFactors = TRUE) -->
<!-- fm1 <- glm(cbind(removed, placed - removed) ~ morph * distance,  -->
<!--            family = binomial(link = "logit"), -->
<!--            data = moth) -->
<!-- summary(fm1) -->
<!-- ``` -->
<!-- Grouped binary data are often overdispersed relative to the variance implied by a binomial distribution.  In this case, we would call the overdispersion "extra-binomial" variation.  As with count data, we can deal with overdispersion through a quasi-likelihood approach: -->
<!-- ```{r} -->
<!-- fm1q <- glm(cbind(removed, placed - removed) ~ morph * distance,  -->
<!--            family = quasibinomial(link = "logit"), -->
<!--            data = moth) -->
<!-- summary(fm1q) -->
<!-- ``` -->
<!-- As with count data, using quasi-likelihood to estimate the scale (or dispersion) parameter increases the estimates of the standard errors of the coefficients by an amount equal to the square root of the estimated scale parameter.   -->
<!-- The $t$-test of the interaction between color morph and distance indicates that there is a statistically significant difference in how the proportion of moth removes changes over the distance transect between the two color morphs. -->
<!-- ```{r} -->
<!-- plot(x = moth$distance,  -->
<!--      y = residuals(fm1q, type = "deviance"), -->
<!--      xlab = "distance", -->
<!--      ylab = "Deviance residuals") -->
<!-- abline(h = 0, lty = "dashed") -->
<!-- ``` -->
<!-- The plot of the residuals suggests that we should include a random effect for the sampling station.  This makes complete sense.  The data for the two color morphs at each station share whatever other characteristics make the station unique, and are thus correlated.  To account for this correlation, we need to introduce a random effect for the station.  This again gets us into the world of generalized linear mixed models.  Before proceeding, we'll write the model down.  Let $i=1,2$ index the two color morphs, and let $j = 1, \ldots, 7$ index the stations.  Let $y_{ij}$ be the number of moths removed, let $n_{ij}$ be the number of moths placed, and let $x_j$ be the distance of the station from Liverpool.  We wish to fit the model -->
<!-- \begin{align*} -->
<!-- y_{ij} & \sim \mathrm{Binom}(p_{ij}, n_{ij})\\ -->
<!-- \mathrm{logit}(p_{ij})  & = \eta_{ij} \\ -->
<!-- \eta_{ij} & = a_i + b_i x_j + L_j \\ -->
<!-- L_j & \sim \mathcal{N}(0, \sigma^2_L) -->
<!-- \end{align*} -->
<!-- The $L_j$'s are our [l]ocation-specific random effects that capture any other station-to-station differences above and beyond the station's distance from Liverpool.  (It turns out that an observation-level random effect does not improve the model, at least as indicated by DIC.)  Because this model includes both a random effect for the station and a non-Gaussian response, it is a generalized linear mixed model (GLMM).  We postpone our discussion accordingly. -->
<!-- We have already mentioned that the $t$-statistics reported in `summary.glm` are based on standard errors calculated from the curvature (Hessian) of the negative log-likelihood at the MLEs, with df determined by the df available for the residual deviance.  An alternative approach for testing for the significance of model terms is to use the residual deviance to compare nested models, much as one would use $F$-tests to compare nested models in ordinary least squares.  Here is a bit of theory.  Let $D$ denote the residual deviance for a model.  Suppose we are comparing two nested models: a parameter poor model that we call model 0, and a parameter rich model that we call model 1.  The parameter-rich model nests the parameter poor model.  Let $p_0$ and $p_1$ be the number of estimated parameters in the linear predictor of models 0 and 1, respectively, and let $D_0$ and $D_1$ denote the (residual) deviances of both models.  In the usual way, we wish to test whether or not the parameter-rich model provides a statistically significant improvement in fit over the parameter-poor model. -->
<!-- There are two separate approaches here depending on whether the scale parameter is known, or is estimated from the data.  If the scale parameter is known to be $\phi$, then define the scaled deviance as $D^* = D / \phi$.  The LRT to compare the two models is equal to the drop in the scaled deviance, $D^*_0 - D^*_1$.  Under the null hypothesis that the parameter-poor model generated the data, the test statistic has a $\chi^2$ distribution with $p_1 - p_0$ degrees of freedom. -->
<!-- If the scale parameter is estimated from the data, then we work with the (residual) deviances directly.  In this case, we calculate the $F$-statistic -->
<!-- $$ -->
<!-- F = \frac{(D_0 - D_1)/(p_1 - p_0)}{D_1 / (n - p_1)}. -->
<!-- $$ -->
<!-- Note that this is generalization of the usual $F$-statistic for comparing nested models from OLS.  Under the null hypothesis, the test statistic has an $F_{p_1 - p_0, n - p_1}$ distribution. -->
<!-- # test for interaction between distance and morph -->
<!-- ```{r} -->
<!-- fm2q <- glm(cbind(removed, placed - removed) ~ morph + distance,  -->
<!--             family = quasibinomial(link = "logit"), -->
<!--             data = moth) -->
<!-- anova(fm2q, fm1q, test = "F") -->
<!-- ``` -->
</div>
</div>
<div id="poisson-regression" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Poisson regression<a href="generalized-linear-models.html#poisson-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Poisson regression is used when the response is a “count” variable. A count variable just counts the number of times that an event occurs. Thus count variables are necessarily non-negative integers.</p>
<p>These data are originally from <span class="citation">Poole (<a href="#ref-poole1989mate">1989</a>)</span>, and were analyzed in <span class="citation">Ramsey and Schafer (<a href="#ref-ramsey2012statistical">2012</a>)</span>. They describe an observational study of 41 male elephants over 8 years at Amboseli National Park in Kenya. Each record in this data set gives the age of a male elephant at the beginning of a study and the number of successful matings for the elephant over the study’s duration. The number of matings is a count variable. Our goal is to characterize how the number of matings is related to the elephant’s age.</p>
<p>Poisson regression is sometimes called “log-linear” regression. In Poisson regression, we try to fit a model for the (natural) log of the average response.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="generalized-linear-models.html#cb153-1" tabindex="-1"></a>elephant <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/elephant.txt&quot;</span>, <span class="at">head =</span> T)</span>
<span id="cb153-2"><a href="generalized-linear-models.html#cb153-2" tabindex="-1"></a><span class="fu">head</span>(elephant)</span></code></pre></div>
<pre><code>##   age matings
## 1  27       0
## 2  28       1
## 3  28       1
## 4  28       1
## 5  28       3
## 6  29       0</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="generalized-linear-models.html#cb155-1" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span></code></pre></div>
<p><img src="04-GeneralizedLinearModels_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="generalized-linear-models.html#cb156-1" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(matings <span class="sc">~</span> age, </span>
<span id="cb156-2"><a href="generalized-linear-models.html#cb156-2" tabindex="-1"></a>           <span class="at">family =</span> poisson, </span>
<span id="cb156-3"><a href="generalized-linear-models.html#cb156-3" tabindex="-1"></a>           <span class="at">data   =</span> elephant)  </span>
<span id="cb156-4"><a href="generalized-linear-models.html#cb156-4" tabindex="-1"></a></span>
<span id="cb156-5"><a href="generalized-linear-models.html#cb156-5" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = matings ~ age, family = poisson, data = elephant)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.58201    0.54462  -2.905  0.00368 ** 
## age          0.06869    0.01375   4.997 5.81e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 75.372  on 40  degrees of freedom
## Residual deviance: 51.012  on 39  degrees of freedom
## AIC: 156.46
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Thus the so-called pseudo-<span class="math inline">\(R^2\)</span> for the model with the log link is
<span class="math display">\[
\mathrm{pseudo}-R^2 = 1 - \frac{51.012}{75.372} = 32.3\%
\]</span>
We can visualize the fit by plotting a best-fitting line with a 95% confidence interval.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="generalized-linear-models.html#cb158-1" tabindex="-1"></a>new.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb158-2"><a href="generalized-linear-models.html#cb158-2" tabindex="-1"></a>                                 <span class="at">to   =</span> <span class="fu">max</span>(elephant<span class="sc">$</span>age),</span>
<span id="cb158-3"><a href="generalized-linear-models.html#cb158-3" tabindex="-1"></a>                                 <span class="at">length =</span> <span class="dv">100</span>))</span>
<span id="cb158-4"><a href="generalized-linear-models.html#cb158-4" tabindex="-1"></a></span>
<span id="cb158-5"><a href="generalized-linear-models.html#cb158-5" tabindex="-1"></a>predict.fm1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm1, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb158-6"><a href="generalized-linear-models.html#cb158-6" tabindex="-1"></a></span>
<span id="cb158-7"><a href="generalized-linear-models.html#cb158-7" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb158-8"><a href="generalized-linear-models.html#cb158-8" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm1<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb158-9"><a href="generalized-linear-models.html#cb158-9" tabindex="-1"></a></span>
<span id="cb158-10"><a href="generalized-linear-models.html#cb158-10" tabindex="-1"></a><span class="co"># add lines for standard errors</span></span>
<span id="cb158-11"><a href="generalized-linear-models.html#cb158-11" tabindex="-1"></a></span>
<span id="cb158-12"><a href="generalized-linear-models.html#cb158-12" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb158-13"><a href="generalized-linear-models.html#cb158-13" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb158-14"><a href="generalized-linear-models.html#cb158-14" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb158-15"><a href="generalized-linear-models.html#cb158-15" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb158-16"><a href="generalized-linear-models.html#cb158-16" tabindex="-1"></a></span>
<span id="cb158-17"><a href="generalized-linear-models.html#cb158-17" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb158-18"><a href="generalized-linear-models.html#cb158-18" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm1<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> predict.fm1<span class="sc">$</span>se.fit, </span>
<span id="cb158-19"><a href="generalized-linear-models.html#cb158-19" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb158-20"><a href="generalized-linear-models.html#cb158-20" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="04-GeneralizedLinearModels_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Unlike logistic regression, with Poisson regression we can generate meaningful residuals. There are two ways to define the residuals for generalized linear models. Here, we’ll have a look at the so-called deviance residuals.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="generalized-linear-models.html#cb159-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> elephant<span class="sc">$</span>age, </span>
<span id="cb159-2"><a href="generalized-linear-models.html#cb159-2" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">residuals</span>(fm1, <span class="at">type =</span> <span class="st">&quot;deviance&quot;</span>),</span>
<span id="cb159-3"><a href="generalized-linear-models.html#cb159-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;age&quot;</span>,</span>
<span id="cb159-4"><a href="generalized-linear-models.html#cb159-4" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Deviance residuals&quot;</span>)</span>
<span id="cb159-5"><a href="generalized-linear-models.html#cb159-5" tabindex="-1"></a></span>
<span id="cb159-6"><a href="generalized-linear-models.html#cb159-6" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="04-GeneralizedLinearModels_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The residuals do not suggest any deficiency in the fit.</p>
<p>With Poisson data, we also have to be wary of so-called overdispersion. In Poisson regression, the assumption of a Poisson-distributed response introduces a very specific assumption about the relationship between the variance of the response and the mean. (Do you remember what this is? In a Poisson distribution, the variance equals the mean!). But this assumption is just an assumption, and its suitability needs to be assessed.</p>
<p>More often than not (dare we say almost always?), the data are more variable, or more dispersed, then the Poisson distribution would suggest. When this happens, we say that the data are “overdispersed” relative to a Poisson distribution. (Underdispersion is possible too, but it’s rare, and for reasons that we will see shortly, it doesn’t create the same statistical problems that overdispersion does.)</p>
<p>Here’s some good news: the degree of over-/under-dispersion is measured by the ratio of something called the “residual deviance” to the df associated with the residual deviance. The residual deviance is the counterpart to the error sum-of-squares in general linear models, and the associated df are computed in the same way. When the ratio of the residual deviance to its df is <span class="math inline">\(&gt;1\)</span>, this suggests overdispersion; when the ratio is <span class="math inline">\(&lt;1\)</span>, this suggest underdispersion. No surprise, the elephant data are overdispersed.</p>
<p>When data are overdispersed, the “naive” standard errors (i.e., those calculated assuming Poisson variation) are too small. That’s bad, and we need to correct for it. (When data are underdispersed, the naive standard errors are too big, which just means we wind up with conservative inferences, which no one worries about.) In R, the way to correct for overdispersion is to use a so-called <code>quasipoisson</code> family. Let’s try it:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="generalized-linear-models.html#cb160-1" tabindex="-1"></a>fm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(matings <span class="sc">~</span> age, <span class="at">family =</span> quasipoisson, <span class="at">data =</span> elephant)  </span>
<span id="cb160-2"><a href="generalized-linear-models.html#cb160-2" tabindex="-1"></a></span>
<span id="cb160-3"><a href="generalized-linear-models.html#cb160-3" tabindex="-1"></a><span class="fu">summary</span>(fm3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = matings ~ age, family = quasipoisson, data = elephant)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.58201    0.58590  -2.700   0.0102 *  
## age          0.06869    0.01479   4.645 3.81e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 1.157334)
## 
##     Null deviance: 75.372  on 40  degrees of freedom
## Residual deviance: 51.012  on 39  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="generalized-linear-models.html#cb162-1" tabindex="-1"></a>predict.fm3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fm3, <span class="at">newdata =</span> new.data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb162-2"><a href="generalized-linear-models.html#cb162-2" tabindex="-1"></a></span>
<span id="cb162-3"><a href="generalized-linear-models.html#cb162-3" tabindex="-1"></a><span class="fu">with</span>(elephant, <span class="fu">plot</span>(matings <span class="sc">~</span> age))</span>
<span id="cb162-4"><a href="generalized-linear-models.html#cb162-4" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> new.data<span class="sc">$</span>age, <span class="at">y =</span> predict.fm3<span class="sc">$</span>fit, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb162-5"><a href="generalized-linear-models.html#cb162-5" tabindex="-1"></a></span>
<span id="cb162-6"><a href="generalized-linear-models.html#cb162-6" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb162-7"><a href="generalized-linear-models.html#cb162-7" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm3<span class="sc">$</span>fit <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="dv">39</span>) <span class="sc">*</span> predict.fm3<span class="sc">$</span>se.fit, </span>
<span id="cb162-8"><a href="generalized-linear-models.html#cb162-8" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb162-9"><a href="generalized-linear-models.html#cb162-9" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb162-10"><a href="generalized-linear-models.html#cb162-10" tabindex="-1"></a></span>
<span id="cb162-11"><a href="generalized-linear-models.html#cb162-11" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x   =</span> new.data<span class="sc">$</span>age, </span>
<span id="cb162-12"><a href="generalized-linear-models.html#cb162-12" tabindex="-1"></a>      <span class="at">y   =</span> predict.fm3<span class="sc">$</span>fit <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">39</span>) <span class="sc">*</span> predict.fm3<span class="sc">$</span>se.fit, </span>
<span id="cb162-13"><a href="generalized-linear-models.html#cb162-13" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb162-14"><a href="generalized-linear-models.html#cb162-14" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="04-GeneralizedLinearModels_files/figure-html/unnamed-chunk-12-1.png" width="672" />
Switching from a Poisson family to a quasi-Poisson family hasn’t changed the parameter estimates of the fit, but it has increased the associate standard errors. To be precise, the standard errors have been multiplied by something called the “dispersion parameter”, which in this case is about 1.16. So, the standard errors have increased by 16% — nothing dramatic, but big enough that we need to account for it. The dispersion parameter should be close to the square root of the ratio of the residual deviance to its df; I’m not sure why it isn’t exactly that value in this case.</p>
<hr />
<p><span style="color: gray;">So what’s “quasi” about a quasi-Poisson family? In the first case, there is no such thing as a “quasi-Poisson” distribution. The “quasi-Poisson” family is just a Poisson fit with the standard errors inflated by the dispersion parameter.</span></p>
<p><span style="color: gray;">You may also wonder why we didn’t discuss overdispersion in logistic regression. In logistic regression with individual responses, like the Donner party data and the boar data, it’s hard to define overdispersion. For logistic regression with grouped binary responses, however, overdispersion can and should be accounted for, just like in Poisson regression. (Grouped responses are those where each data point is not a single success or failure, but a tally of the number of successes in many trials.) There is a <code>quasibinomial</code> family in R to deal with overdispersed (grouped) binomial data.</span></p>
<hr />
<!-- As an alternative, we could fit a model that uses a negative binomial distribution for the response.  Negative binomial distributions belong to the exponential family, so we can fit them using the GLM framework.  However, the authors of `glm` did not include a negative binomial family in their initial code.  Venables & Ripley's `MASS` package includes a program called `glm.nb` which is specifically designed for negative binomial responses.  `MASS::glm.nb` uses the parameterization familiar to ecologists, although they use the parameter $\theta$ instead of $k$.  So, in their notation, if $y \sim \mathrm{NB}(\mu, \theta)$, then $\mathrm{Var}(y) = \mu + \mu^2/\theta$. -->
<!-- ```{r} -->
<!-- require(MASS) -->
<!-- fm4 <- glm.nb(matings ~ age, link = identity, data = elephant)   -->
<!-- summary(fm4) -->
<!-- predict.fm4 <- predict(fm4, newdata = new.data, type = "response", se.fit = TRUE) -->
<!-- with(elephant, plot(matings ~ age)) -->
<!-- lines(x = new.data$age, y = predict.fm4$fit, col = "blue") -->
<!-- lines(x   = new.data$age,  -->
<!--       y   = predict.fm4$fit + 1.96 * predict.fm4$se.fit,  -->
<!--       col = "blue", -->
<!--       lty = "dashed") -->
<!-- lines(x   = new.data$age,  -->
<!--       y   = predict.fm4$fit - 1.96 * predict.fm4$se.fit,  -->
<!--       col = "blue", -->
<!--       lty = "dashed") -->
<!-- ``` -->
<!-- Notice that $\hat{\theta} = 15.8$, again indicating that the extra-Poisson variation is mild.  Notice also that the error bounds on the fitted curve are ever so slightly larger than the error bounds from the Poisson fit, and nearly identical to the error bounds from the quasi-Poisson fit. -->

</div>
</div>



<h3>Bibliography<a href="bibliography.html#bibliography" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-grayson1993differential" class="csl-entry">
Grayson, Donald K. 1993. <span>“Differential Mortality and the Donner Party Disaster.”</span> <em>Evolutionary Anthropology: Issues, News, and Reviews</em> 2 (5): 151–59.
</div>
<div id="ref-poole1989mate" class="csl-entry">
Poole, Joyce H. 1989. <span>“Mate Guarding, Reproductive Success and Female Choice in African Elephants.”</span> <em>Animal Behaviour</em> 37: 842–49.
</div>
<div id="ref-ramsey2012statistical" class="csl-entry">
Ramsey, Fred, and Daniel Schafer. 2012. <em>The Statistical Sleuth: A Course in Methods of Data Analysis</em>. Pacific Grove, CA: Duxbury.
</div>
<div id="ref-vicente2006wild" class="csl-entry">
Vicente, Joaquı́n, Ursula Höfle, Joseba Garrido, Isabel G Fernández-De-Mera, Ramón Juste, Marta Barral, and Christian Gortazar. 2006. <span>“Wild Boar and Red Deer Display High Prevalences of Tuberculosis-Like Lesions in Spain.”</span> <em>Veterinary Research</em> 37 (1): 107–19.
</div>
<div id="ref-zuur2009mixed" class="csl-entry">
Zuur, Alain F, Elena N Ieno, Neil J Walker, Anatoly A Saveliev, Graham M Smith, et al. 2009. <em>Mixed Effects Models and Extensions in Ecology with <span>R</span></em>. New York: Springer.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="non-linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="smoothing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "serif",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
